[package]
name = "cmd"
version = "0.1.0"
authors = ["Jamie Bliss <jamie@ivyleav.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rcon = "0.1.0"
localmc = { path = "../localmc" }
failure = "0.1.6"
